<?php

 
array ( 
	0 => array ( 
		'id' => '1', 'title' => '品牌管理', 'pid' => '0', 'sort' => '1', 'url' => 'Brand/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '1', 'icon' => 'icon-sitemap', 
		'child' => array (
		 0 => array ( 'id' => '14', 'title' => '员工管理', 'pid' => '1', 'sort' => '0', 'url' => 'Brand/Employee/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '1', 'icon' => '', 'child' => NULL, ),
		 1 => array ( 'id' => '15', 'title' => '会员批量延期', 'pid' => '1', 'sort' => '0', 'url' => 'Brand/Shop/delay', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '1', 'icon' => '', 'child' => NULL, ), 
		 2 => array ( 'id' => '16', 'title' => '会籍合同查询', 'pid' => '1', 'sort' => '0', 'url' => 'Brand/Mcontract/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '1', 'icon' => '', 'child' => NULL, ),
		 3 => array ( 'id' => '83', 'title' => '发送通知', 'pid' => '1', 'sort' => '0', 'url' => 'Brand/Notice/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '1', 'icon' => '', 'child' => NULL, ),
		 4 => array ( 'id' => '17', 'title' => '基础设置', 'pid' => '1', 'sort' => '0', 'url' => 'Brand/Shop/config', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '1', 'icon' => '', 'child' => array ( 
		 	 0 => array ( 'id' => '19', 'title' => '会所信息管理', 'pid' => '17', 'sort' => '0', 'url' => 'Brand/Shop/clubsinfo', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '1', 'icon' => 'icon-leaf', ),
		 	 1 => array ( 'id' => '20', 'title' => '高峰时段设置', 'pid' => '17', 'sort' => '0', 'url' => 'Brand/Shop/peak', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '1', 'icon' => 'icon-leaf', ), 
		 	 2 => array ( 'id' => '21', 'title' => '商品管理', 'pid' => '17', 'sort' => '0', 'url' => 'Brand/Goods/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '1', 'icon' => 'icon-leaf', ), 
		 	 3 => array ( 'id' => '22', 'title' => 'PT课程设置', 'pid' => '17', 'sort' => '0', 'url' => 'Brand/Ptclass/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '1', 'icon' => 'icon-leaf', ), 
		 	 4 => array ( 'id' => '23', 'title' => '卡种设置', 'pid' => '17', 'sort' => '0', 'url' => 'Brand/Cardtype/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '1', 'icon' => 'icon-leaf', ), 
		 	 5 => array ( 'id' => '24', 'title' => '系统设置', 'pid' => '17', 'sort' => '0', 'url' => 'Brand/Systemconfig/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '1', 'icon' => 'icon-leaf', ), ), ), 
        5 => array ( 'id' => '18', 'title' => '稽核', 'pid' => '1', 'sort' => '0', 'url' => 'Brand/Review/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '1', 'icon' => '', 'child' => array (
            0 => array ( 'id' => '25', 'title' => '会籍合同审批', 'pid' => '18', 'sort' => '0', 'url' => 'Brand/Review/contract', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '1', 'icon' => 'icon-leaf', ), 
            1 => array ( 'id' => '26', 'title' => 'PT合同审批', 'pid' => '18', 'sort' => '0', 'url' => 'Brand/Review/ptcontract', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '1', 'icon' => 'icon-leaf', ), 
            2 => array ( 'id' => '27', 'title' => '退会申请', 'pid' => '18', 'sort' => '0', 'url' => 'Brand/Review/quit', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '1', 'icon' => 'icon-leaf', ), 
            3 => array ( 'id' => '28', 'title' => '消费明细', 'pid' => '18', 'sort' => '0', 'url' => 'Brand/Review/consume', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '1', 'icon' => 'icon-leaf', ), 
            4 => array ( 'id' => '68', 'title' => '消费记录修改', 'pid' => '18', 'sort' => '0', 'url' => 'Brand/Review/paymodify', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => 'icon-leaf', ), ), ), ), 
       ), 
   1 => array ( 'id' => '2', 'title' => '店长', 'pid' => '0', 'sort' => '2', 'url' => 'Shopkeeper/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '1', 'icon' => 'icon-home', 'child' => array ( 
   	   0 => array ( 'id' => '29', 'title' => '员工管理', 'pid' => '2', 'sort' => '0', 'url' => 'Shopkeeper/Employee/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), 
   	   1 => array ( 'id' => '76', 'title' => '课程安排', 'pid' => '2', 'sort' => '0', 'url' => 'Shopkeeper/Class/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), 
   	   2 => array ( 'id' => '80', 'title' => '教室管理', 'pid' => '2', 'sort' => '0', 'url' => 'Shopkeeper/Room/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), 
   	   3 => array ( 'id' => '81', 'title' => '老师课程', 'pid' => '2', 'sort' => '0', 'url' => 'Shopkeeper/Tclass/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), ), ),
    2 => array ( 'id' => '3', 'title' => '财务', 'pid' => '0', 'sort' => '3', 'url' => 'Finance/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '1', 'icon' => 'icon-bar-chart', 'child' => array ( 
       0 => array ( 'id' => '64', 'title' => '财务报表', 'pid' => '3', 'sort' => '0', 'url' => 'Finance/Report/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), 
       1 => array ( 'id' => '65', 'title' => '商品销售报表', 'pid' => '3', 'sort' => '0', 'url' => 'Finance/Goods/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), 
       2 => array ( 'id' => '66', 'title' => '销售业绩报表', 'pid' => '3', 'sort' => '0', 'url' => 'Finance/McReport/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), 
       3 => array ( 'id' => '67', 'title' => '入账记录', 'pid' => '3', 'sort' => '0', 'url' => 'Finance/Payhistory/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), 
       4 => array ( 'id' => '69', 'title' => '退款', 'pid' => '3', 'sort' => '0', 'url' => 'Finance/Contract/payback', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), ), ), 
    3 => array ( 'id' => '4', 'title' => '前台', 'pid' => '0', 'sort' => '4', 'url' => 'Reception/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '1', 'icon' => 'icon-coffee', 'child' => array ( 
    	0 => array ( 'id' => '33', 'title' => '来访登记', 'pid' => '4', 'sort' => '0', 'url' => 'Reception/Visit/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), 
    	1 => array ( 'id' => '44', 'title' => '会员卡管理', 'pid' => '4', 'sort' => '0', 'url' => 'Reception/Cardmanage/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), 
    	2 => array ( 'id' => '70', 'title' => '预约签到', 'pid' => '4', 'sort' => '0', 'url' => 'Reception/Invit/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), 
    	3 => array ( 'id' => '72', 'title' => 'PT消课', 'pid' => '4', 'sort' => '0', 'url' => 'Reception/Pt/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), 
    	4 => array ( 'id' => '75', 'title' => '进出馆明细', 'pid' => '4', 'sort' => '0', 'url' => 'Reception/Consume/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), 
    	5 => array ( 'id' => '82', 'title' => '约课记录', 'pid' => '4', 'sort' => '0', 'url' => 'Reception/Appoint/checkappoint', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), 
    	6 => array ( 'id' => '84', 'title' => '惩罚记录', 'pid' => '4', 'sort' => '0', 'url' => 'Reception/Appoint/appointblacklist', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), 
    	7 => array ( 'id' => '81', 'title' => 'Yaa Gift', 'pid' => '4', 'sort' => '0', 'url' => 'Reception/Yaa/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), ), ), 
    4 => array ( 'id' => '5', 'title' => '水吧', 'pid' => '0', 'sort' => '5', 'url' => 'Bar/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '1', 'icon' => 'icon-beer', 'child' => array ( 
    	0 => array ( 'id' => '46', 'title' => '商品销售', 'pid' => '5', 'sort' => '0', 'url' => 'Bar/Goods/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), 
    	1 => array ( 'id' => '47', 'title' => '卖品流水', 'pid' => '5', 'sort' => '0', 'url' => 'Bar/Goods/list', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), ), ), 
    5 => array ( 'id' => '6', 'title' => '收银', 'pid' => '0', 'sort' => '6', 'url' => 'Cashier/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '1', 'icon' => 'icon-money', 'child' => array ( 
    	0 => array ( 'id' => '37', 'title' => '会员入会', 'pid' => '6', 'sort' => '0', 'url' => 'Cashier/Member/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), 
    	1 => array ( 'id' => '38', 'title' => '会籍合同管理', 'pid' => '6', 'sort' => '0', 'url' => 'Cashier/Contract/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), 
    	2 => array ( 'id' => '39', 'title' => 'PT合同管理', 'pid' => '6', 'sort' => '0', 'url' => 'Cashier/Ptcontract/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), 
    	3 => array ( 'id' => '40', 'title' => '卡种查询', 'pid' => '6', 'sort' => '0', 'url' => 'Cashier/Cardtype/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), 
    	4 => array ( 'id' => '41', 'title' => '消费明细', 'pid' => '6', 'sort' => '0', 'url' => 'Cashier/Consume/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), 
    	5 => array ( 'id' => '45', 'title' => '充值卡管理', 'pid' => '6', 'sort' => '0', 'url' => 'Cashier/Recharge/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), 
    	6 => array ( 'id' => '63', 'title' => 'PT购买', 'pid' => '6', 'sort' => '0', 'url' => 'Cashier/Pt/sale', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), 
    	7 => array ( 'id' => '73', 'title' => '定金收银', 'pid' => '6', 'sort' => '0', 'url' => 'Cashier/Book/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), 
    	8 => array ( 'id' => '74', 'title' => '收银报表', 'pid' => '6', 'sort' => '0', 'url' => 'Cashier/Report/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), ), ), 
	6 => array ( 'id' => '7', 'title' => 'MC经理', 'pid' => '0', 'sort' => '7', 'url' => 'Mcmanager/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '1', 'icon' => 'icon-user-md', 'child' => array ( 
		0 => array ( 'id' => '54', 'title' => '潜客管理', 'pid' => '7', 'sort' => '0', 'url' => 'Mcmanager/Member/notmember', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), 
		1 => array ( 'id' => '55', 'title' => '会员管理', 'pid' => '7', 'sort' => '0', 'url' => 'Mcmanager/Member/ismember', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), 
		2 => array ( 'id' => '56', 'title' => 'MC销售跟进', 'pid' => '7', 'sort' => '0', 'url' => 'Mcmanager/Mcsale/followuplist', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), 
		3 => array ( 'id' => '57', 'title' => 'MC会员跟进', 'pid' => '7', 'sort' => '0', 'url' => 'Mcmanager/Mcsale/servicelist', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), 
		4 => array ( 'id' => '58', 'title' => 'MC业绩统计', 'pid' => '7', 'sort' => '0', 'url' => 'Mcmanager/Mcstatistics/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), 
		5 => array ( 'id' => '59', 'title' => 'MC分组', 'pid' => '7', 'sort' => '0', 'url' => 'Mcmanager/Group/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), 
		6 => array ( 'id' => '71', 'title' => '计划New', 'pid' => '7', 'sort' => '0', 'url' => 'Mcmanager/Plannew/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), ), ), 
    7 => array ( 'id' => '8', 'title' => 'MC', 'pid' => '0', 'sort' => '8', 'url' => 'Mc/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '1', 'icon' => 'icon-user', 'child' => array ( 
    	0 => array ( 'id' => '42', 'title' => '增加潜客', 'pid' => '8', 'sort' => '0', 'url' => 'Mc/Visit/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), 
    	1 => array ( 'id' => '48', 'title' => '我的潜客', 'pid' => '8', 'sort' => '0', 'url' => 'Mc/Visit/mynotmemberlist', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), 
    	2 => array ( 'id' => '49', 'title' => '销售跟进', 'pid' => '8', 'sort' => '0', 'url' => 'Mc/Manage/sale', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), 
    	3 => array ( 'id' => '50', 'title' => '我的预约', 'pid' => '8', 'sort' => '0', 'url' => 'Mc/Manage/myappoint', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), 
    	4 => array ( 'id' => '51', 'title' => '卡种查询', 'pid' => '8', 'sort' => '0', 'url' => 'Mc/Cardtype/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), 
    	5 => array ( 'id' => '52', 'title' => '我的会员', 'pid' => '8', 'sort' => '0', 'url' => 'Mc/Visit/myismemberlist', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), 
    	6 => array ( 'id' => '53', 'title' => '会员跟进', 'pid' => '8', 'sort' => '0', 'url' => 'Mc/Manage/service', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), 
    	7 => array ( 'id' => '60', 'title' => '英雄榜', 'pid' => '8', 'sort' => '0', 'url' => 'Mc/List/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), 
    	8 => array ( 'id' => '85', 'title' => '组员潜客', 'pid' => '8', 'sort' => '0', 'url' => 'Mc/Group/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), ), ), 
    8 => array ( 'id' => '9', 'title' => 'PT经理', 'pid' => '0', 'sort' => '9', 'url' => 'Ptmanager/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '1', 'icon' => 'icon-user-md', 'child' => array ( 
    	0 => array ( 'id' => '61', 'title' => '会员管理', 'pid' => '9', 'sort' => '0', 'url' => 'Ptmanager/Member/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), ), ), 
    9 => array ( 'id' => '10', 'title' => 'PT', 'pid' => '0', 'sort' => '10', 'url' => 'Pt/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '1', 'icon' => 'icon-user', 'child' => array ( 
    	0 => array ( 'id' => '86', 'title' => '会员管理', 'pid' => '10', 'sort' => '0', 'url' => 'Pt/Member/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), 
    	1 => array ( 'id' => '62', 'title' => '销售跟进', 'pid' => '10', 'sort' => '0', 'url' => 'Pt/Sale/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), 
    	2 => array ( 'id' => '77', 'title' => '课程管理', 'pid' => '10', 'sort' => '0', 'url' => 'Pt/Class/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), 
    	3 => array ( 'id' => '78', 'title' => '我的课表', 'pid' => '10', 'sort' => '0', 'url' => 'Pt/Schedule/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), 
    	4 => array ( 'id' => '79', 'title' => '上课记录', 'pid' => '10', 'sort' => '0', 'url' => 'Pt/Report/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), 
    	5 => array ( 'id' => '84', 'title' => '增加潜客', 'pid' => '10', 'sort' => '0', 'url' => 'Pt/Visit/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), ), ), 
    10 => array ( 'id' => '12', 'title' => '渠道经理', 'pid' => '0', 'sort' => '12', 'url' => 'Channelmanager/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '1', 'icon' => 'icon-user-md', 'child' => array ( 
    	0 => array ( 'id' => '30', 'title' => '渠道计划', 'pid' => '12', 'sort' => '0', 'url' => 'Channelmanager/Plan/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), 
    	1 => array ( 'id' => '31', 'title' => '渠道管理', 'pid' => '12', 'sort' => '0', 'url' => 'Channelmanager/Channel/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), 
    	2 => array ( 'id' => '35', 'title' => '渠道统计', 'pid' => '12', 'sort' => '0', 'url' => 'Channelmanager/Statistics/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), ), ), 
    11 => array ( 'id' => '13', 'title' => '渠道', 'pid' => '0', 'sort' => '13', 'url' => 'Channel/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '1', 'icon' => 'icon-user', 'child' => array ( 
    	0 => array ( 'id' => '32', 'title' => '跟进记录', 'pid' => '13', 'sort' => '0', 'url' => 'Channel/Visit/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), 
    	1 => array ( 'id' => '34', 'title' => '增加潜在客户', 'pid' => '13', 'sort' => '0', 'url' => 'Channel/Visitn/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), 
    	2 => array ( 'id' => '36', 'title' => '渠道统计', 'pid' => '13', 'sort' => '0', 'url' => 'Channel/Statistics/index', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), 
    	3 => array ( 'id' => '43', 'title' => '客户管理', 'pid' => '13', 'sort' => '0', 'url' => 'Channel/Visitn/myallmemberlist', 'hide' => '0', 'tip' => '', 'group' => '', 'is_dev' => '0', 'status' => '0', 'icon' => '', 'child' => NULL, ), ), ), );